# Generated by Django 3.0.3 on 2020-03-05 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('entry_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='入部年度')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Member',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='バンド名')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='メモ')),
                ('members', models.ManyToManyField(to='dosuke.Member', verbose_name='メンバー')),
            ],
            options={
                'verbose_name': 'Band',
                'verbose_name_plural': 'Band',
            },
        ),
    ]
