# Generated by Django 3.0.3 on 2020-02-21 11:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('band_list', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=30, size=None)),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Item',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
