# Generated by Django 3.0.3 on 2020-02-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuke', '0002_auto_20200221_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Event'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Item'},
        ),
    ]
