# Generated by Django 3.0.3 on 2020-03-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuke', '0002_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Config', 'verbose_name_plural': 'Config'},
        ),
    ]
