# Generated by Django 3.0.3 on 2020-02-21 12:15

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuke', '0003_auto_20200221_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='band_list',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6),
        ),
    ]
