# Generated by Django 3.0.3 on 2020-02-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuke', '0004_auto_20200221_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
