# Generated by Django 3.0.3 on 2020-02-23 22:32

import django.core.validators
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuke', '0005_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('member_list', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Band',
                'verbose_name_plural': 'Band',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('entry_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='entry_year')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Member',
            },
        ),
    ]
