# Generated by Django 3.0.3 on 2020-02-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuke', '0006_band_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='band',
            field=models.ManyToManyField(to='dosuke.Band'),
        ),
    ]
