# Generated by Django 3.0.3 on 2020-02-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuke', '0009_auto_20200223_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='memo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='memo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='memo'),
        ),
    ]
