# Generated by Django 3.0.3 on 2020-02-26 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuke', '0011_auto_20200224_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='band',
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(to='dosuke.Member'),
        ),
        migrations.AlterField(
            model_name='band',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=20, verbose_name='バンド名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='entry_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='入部年度'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
    ]
